version: '3'
services:
  web:
    build: .
    image: laravel-app
    container_name: laravel-web
    environment:
      CONTAINER_ROLE: web
      DB_HOST: mysql
      REDIS_HOST: redisdb
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
    ports:
      - 8080:2015
    links:
      - redisdb
      - mysql
  scheduler:
    image: laravel-app
    container_name: laravel-scheduler
    environment:
      CONTAINER_ROLE: scheduler
    links:
      - redisdb
      - mysql
  queue:
    image: laravel-app
    container_name: laravel-queue
    environment:
      CONTAINER_ROLE: queue
    links:
      - redisdb
      - mysql
  redisdb:
    container_name: laravel-redis
    image: redis:3.0.7-alpine
    ports:
      - 16379:6379
  mysql:
    container_name: laravel-mysql
    image: mysql:5.7
    ports:
     - 13306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
